//Icons
import Analitika from "../assets/icons/analytics.svg?react";
import Lid from "../assets/icons/lid.svg?react";
import Finance from "../assets/icons/finance.svg?react";
import Students from "../assets/icons/student.svg?react";
import Groups from "../assets/icons/group.svg?react";
import Course from "../assets/icons/course.svg?react";
import HR from "../assets/icons/hr.svg?react";
import Settings from "../assets/icons/setting.svg?react";

import { BiSolidInstitution } from "react-icons/bi";
import { MdOutlineLocalActivity } from "react-icons/md";
import { VscSymbolStructure } from "react-icons/vsc";
import { PiStudentDuotone } from "react-icons/pi";
import { TbNews } from "react-icons/tb";
import { TbMenuDeep } from "react-icons/tb";
import { TfiAnnouncement } from "react-icons/tfi";
import { GoPeople } from "react-icons/go";
import { CgWorkAlt } from "react-icons/cg";
import { MdAccountCircle } from "react-icons/md";
import { TiHome } from "react-icons/ti";

//Components
import Generics from "../view/Generics";

const sidebar = [
  {
    id: 1,
    title: "Yangiliklar",
    path: "/yangiliklar",
    icon: Analitika,
    isPrivate: true,
    element: Generics,
    role: ["admin"],
  },
  {
    id: 2,
    title: "E'lonlar",
    path: "/elonlar",
    icon: Analitika,
    isPrivate: true,
    element: Generics,
    role: ["admin"],
  },
  {
    id: 3,
    title: "Home",
    path: "/home",
    icon: Lid,
    isPrivate: true,
    element: Generics,
    role: ["admin"],
    children: [
      {
        id: `3-1`,
        title: "Hemis tizimi",
        path: "/home/hemis",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-2`,
        title: "Institut jurnali",
        path: "/home/first-class",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-3`,
        title: "Konferensiyalar",
        path: "/home/konfirensiyalar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-4`,
        title: "Ikkinchi ta'lim",
        path: "/home/ikkinchi-ta'lim",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-5`,
        title: "Ochiq manbalar",
        path: "/home/ochiq-manbalar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-6`,
        title: "Asosiy video",
        path: "/home/asosiy-video",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-7`,
        title: "Interaktiv xizmatlar",
        path: "/home/interaktiv-xizmatlar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-8`,
        title: "Statistika",
        path: "/home/statistika",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-9`,
        title: "Talaba fikri",
        path: "/home/talaba-fikri",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-10`,
        title: "Uchtalik video",
        path: "/home/uchtalik-video",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-11`,
        title: "Galleriya",
        path: "/home/galleriya",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-12`,
        title: "Hamkorlar",
        path: "/home/hamkorlar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `3-13`,
        title: "Bog'lanish",
        path: "/home/boglanish",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 4,
    title: "Institut",
    path: "/institut",
    icon: Finance,
    isPrivate: true,
    element: Generics,
    role: ["admin"],
    children: [
      {
        id: `4-1`,
        title: "Institut kengashi",
        path: "/institut/institut-kengashi",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `4-2`,
        title: "Institut haqida",
        path: "/institut/institut-haqida",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `4-3`,
        title: "Institut tuzilmasi",
        path: "/institut/institut-tuzilmasi",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `4-4`,
        title: "Rekvizitlar",
        path: "/institut/rekvizitlar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `4-5`,
        title: "Virtual qabulxona",
        path: "/institut/virtual-qabulxona",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 4,
    title: "Faoliyat",
    path: "/faoliyat",
    icon: Students,
    isPrivate: true,
    element: Generics,
    role: ["admin", "mentor", "manager"],
    children: [
      {
        id: `5-1`,
        title: "Jamoatchilik kengashi",
        path: "/faoliyat/jamoatchilik-kengashi",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `5-2`,
        title: "Madaniy-ma'rifiy",
        path: "/faoliyat/madaniy-marifiy-faoliyat",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `5-3`,
        title: "O'quv-uslubiy",
        path: "/faoliyat/oquv-uslubiy-faoliyat",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `5-4`,
        title: "Akademik litsey",
        path: "/faoliyat/akademik-litsey",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `5-5`,
        title: "Ilmiy faoliyat",
        path: "/faoliyat/ilmiy-faoliyat",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 6,
    title: "Tuzilma",
    path: "/tuzilma",
    icon: Groups,
    isPrivate: true,
    element: Generics,
    role: ["admin", "mentor", "manager"],
    children: [
      {
        id: `6-1`,
        title: "Rektorat",
        path: "/tuzilma/rektorat",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `6-2`,
        title: "Fakultetlar",
        path: "/tuzilma/fakultetlar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `6-3`,
        title: "Kafedralar",
        path: "/tuzilma/kafedralar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `6-4`,
        title: "Bo'limlar",
        path: "/tuzilma/bolimlar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `6-5`,
        title: "Markazlar",
        path: "/tuzilma/markazlar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 7,
    title: "Talabalar",
    path: "/talabalar",
    icon: Course,
    isPrivate: true,
    element: Generics,
    role: ["admin", "mentor", "manager"],
    children: [
      {
        id: `7-1`,
        title: "Bakalavriat",
        path: "/talabalar/bakalavriat",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `7-2`,
        title: "Magistratura",
        path: "/talabalar/magistratura",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `7-3`,
        title: "Talabalar turar joyi",
        path: "/talabalar/talabalar-turar-joyi",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 8,
    title: "Abiturient",
    path: "/abiturient",
    icon: HR,
    isPrivate: true,
    element: Generics,
    role: ["admin", "manager"],
    children: [
      {
        id: `8-1`,
        title: "Bakalavriat",
        path: "/abiturient/abiturient-bakalavriat",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `8-2`,
        title: "Magistratura",
        path: "/abiturient/abiturient-magistratura",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `8-3`,
        title: "Xorijiy talabalar qabul",
        path: "/abiturient/xorijiy-talabalar-qabul",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `8-4`,
        title: "Call markaz",
        path: "/abiturient/call-markaz",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
      {
        id: `8-5`,
        title: "Me'yoriy huquqiy hujjatlar",
        path: "/abiturient/meyoriy-huquqiy-hujjatlar",
        isPrivate: true,
        element: Generics,
        role: ["admin", "manager"],
      },
    ],
  },
  {
    id: 9,
    title: "Bo'sh ish o'rinlari",
    path: "/vakansiyalar",
    icon: Settings,
    isPrivate: true,
    element: Generics,
    role: ["admin", "manager"],
  },
];

export default sidebar;
